### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\Users\s\StudioProjects".

### ISSUE THREAD

**Issue by EternalTitan** [Codelessly/FlutterMinimalWebsite#3]
Running "flutter pub get" in FlutterMinimalWebsite...           
Could not find a file named "pubspec.yaml" in "C:\Users\s\StudioProjects".
pub get failed (66; Could not find a file named "pubspec.yaml" in "C:\Users\s\StudioProjects".)

Looks like caused by this line in pubspec.yaml
     path: ../

**Comment by searchy2** [comment]
This library uses ResponsiveFramework as an embedded submodule. Please try initializing the submodule so those files exist.

**Comment by weypro** [comment]
You can edit `pubspec.yaml` by uncommenting the codes:
```
  responsive_framework:
    git:
      url: https://github.com/Codelessly/ResponsiveFramework.git
      ref: master
```
Or add the line directly:
```
  responsive_framework: ^0.1.4
```
